"""initial schema

Revision ID: c48411bf0a81
Revises: 
Create Date: 2026-09-27 15:55:21.832510

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48411bf0a81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('classifier_algorithm', sa.String(length=50), nullable=False),
    sa.Column('regressor_algorithm', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('ministry', sa.String(length=255), nullable=False),
    sa.Column('implementing_agency', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluk', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('land_proposed_hectares', sa.Float(), nullable=False),
    sa.Column('land_acquired_hectares', sa.Float(), nullable=False),
    sa.Column('acquisition_percentage', sa.Float(), nullable=False),
    sa.Column('affected_families', sa.Integer(), nullable=False),
    sa.Column('displaced_families', sa.Integer(), nullable=False),
    sa.Column('notification_status', sa.String(length=50), nullable=False),
    sa.Column('notification_date', sa.String(length=20), nullable=False),
    sa.Column('survey_status', sa.String(length=50), nullable=False),
    sa.Column('survey_completion_percentage', sa.Float(), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('approval_pending_days', sa.Integer(), nullable=False),
    sa.Column('award_status', sa.String(length=50), nullable=False),
    sa.Column('award_date', sa.String(length=20), nullable=False),
    sa.Column('compensation_assessed', sa.Float(), nullable=False),
    sa.Column('compensation_paid', sa.Float(), nullable=False),
    sa.Column('compensation_pending', sa.Float(), nullable=False),
    sa.Column('legal_cases', sa.Integer(), nullable=False),
    sa.Column('legal_dispute_severity', sa.String(length=20), nullable=False),
    sa.Column('possession_status', sa.String(length=50), nullable=False),
    sa.Column('possession_percentage', sa.Float(), nullable=False),
    sa.Column('rr_status', sa.String(length=50), nullable=False),
    sa.Column('rr_completion_percentage', sa.Float(), nullable=False),
    sa.Column('documentation_completeness', sa.Float(), nullable=False),
    sa.Column('stakeholder_responsiveness', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('planned_completion_date', sa.String(length=20), nullable=False),
    sa.Column('actual_completion_date', sa.String(length=20), nullable=False),
    sa.Column('project_start_date', sa.String(length=20), nullable=False),
    sa.Column('historical_agency_delay_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_current_stage'), 'projects', ['current_stage'], unique=False)
    op.create_index(op.f('ix_projects_district'), 'projects', ['district'], unique=False)
    op.create_index(op.f('ix_projects_implementing_agency'), 'projects', ['implementing_agency'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_state'), 'projects', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CENTRAL_ADMIN', 'STATE_ADMIN', 'DISTRICT_OFFICER', 'PROJECT_OFFICER', 'ANALYST', 'VIEWER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_pk', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_pk'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_project_pk'), 'alerts', ['project_pk'], unique=False)
    op.create_table('data_quality_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_pk', sa.Integer(), nullable=False),
    sa.Column('completeness_percentage', sa.Float(), nullable=False),
    sa.Column('missing_fields_json', sa.Text(), nullable=False),
    sa.Column('has_duplicates', sa.Boolean(), nullable=False),
    sa.Column('has_invalid_dates', sa.Boolean(), nullable=False),
    sa.Column('has_conflicting_values', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_pk'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_records_project_pk'), 'data_quality_records', ['project_pk'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_pk', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_pk'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_pk'), 'documents', ['project_pk'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_pk', sa.Integer(), nullable=False),
    sa.Column('probability_of_delay', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('expected_delay_days', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('classifier_algorithm', sa.String(length=50), nullable=False),
    sa.Column('regressor_algorithm', sa.String(length=50), nullable=False),
    sa.Column('top_positive_drivers_json', sa.Text(), nullable=False),
    sa.Column('top_negative_drivers_json', sa.Text(), nullable=False),
    sa.Column('stage_risks_json', sa.Text(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_pk'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_project_pk'), 'predictions', ['project_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_project_pk'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_documents_project_pk'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_data_quality_records_project_pk'), table_name='data_quality_records')
    op.drop_table('data_quality_records')
    op.drop_index(op.f('ix_alerts_project_pk'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_state'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_implementing_agency'), table_name='projects')
    op.drop_index(op.f('ix_projects_district'), table_name='projects')
    op.drop_index(op.f('ix_projects_current_stage'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
